#
# /etc/zshrc is sourced in interactive shells.
# LunarShell ZSH Configuration
#

# History configuration
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS

# Shell options
setopt autocd
setopt extendedglob
setopt nomatch
setopt notify
unsetopt beep

# Basic auto/tab completion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # Include hidden files

# Set prompts (fallback if starship fails)
PROMPT='[%n@%m]%~%# '
HOSTNAME=$(hostname)

# Key bindings
bindkey ' ' magic-space  # History expansion on space
bindkey '^[[H' beginning-of-line # Home key
bindkey '^[[F' end-of-line # End key
bindkey '^[[3~' delete-char # Del key
bindkey '^[[1;5C' forward-word # Ctrl+Right
bindkey '^[[1;5D' backward-word # Ctrl+Left
bindkey '^[[A' history-beginning-search-backward # Up arrow
bindkey '^[[B' history-beginning-search-forward # Down arrow

# Provide pathmunge for /etc/profile.d scripts
pathmunge() {
    if ! echo $PATH | /bin/grep -qE "(^|:)$1($|:)" ; then
        if [ "$2" = "after" ] ; then
            PATH=$PATH:$1
        else
            PATH=$1:$PATH
        fi
    fi
}

# Source profile.d scripts
_src_etc_profile_d() {
    emulate -L ksh
    if [ -d /etc/profile.d ]; then
        for i in /etc/profile.d/*.sh; do
            if [ -r "$i" ]; then
                . $i
            fi
        done
        unset i
    fi
}
_src_etc_profile_d

# Window title function
function set_win_title() {
    echo -ne "\033]0;${USER}@${HOSTNAME}:$(echo -ne "${PWD}" | sed "s,${HOME},~,")\007"
}
precmd_functions+=(set_win_title)

# Useful aliases
alias ls='ls --color=auto'
alias ll='ls -lah'
alias grep='grep --color=auto'
alias ip='ip -color=auto'

# Load distribution-specific configurations
if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        arch)
            # Arch-specific settings
            alias pacman='pacman --color=auto'
            ;;
        ubuntu|debian)
            # Ubuntu/Debian-specific settings
            alias apt='apt --color=auto'
            ;;
        rhel|centos|rocky|almalinux)
            # RHEL/CentOS/Rocky/Alma-specific settings
            alias dnf='dnf --color=auto'
            ;;
    esac
fi

# Cleanup
unset -f pathmunge _src_etc_profile_d
